import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import fs from "fs";
import path from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

// Where `npm run dev` writes the bundle. Set this to your vault's plugin
// folder (e.g. "/path/to/Vault/.obsidian/plugins/base-board") to auto-deploy
const PLUGIN_DEV_DIR = ".";

// ---------------------------------------------------------------------------
// Plugin: concatenate src/styles/*.css into a single styles.css output
// ---------------------------------------------------------------------------

/**
 * @typedef {Object} ConcatStylesOptions
 * @property {string} inputDir - Directory containing the source CSS files (relative to cwd).
 * @property {string} outputFile - Output filename for the concatenated stylesheet.
 */

/**
 * @param {ConcatStylesOptions} options
 * @returns {esbuild.Plugin}
 */
function concatStylesPlugin(options) {
  return {
    name: "concat-styles",
    setup(build) {
      build.onEnd(() => {
        const inputDir = path.resolve(build.initialOptions.outdir || ".", options.inputDir);
        const outputFile = path.resolve(build.initialOptions.outdir || ".", options.outputFile);

        // Find all .css files in the input directory
        const cssFiles = fs
          .readdirSync(inputDir)
          .filter((f) => f.endsWith(".css"))
          .sort(); // deterministic order

        if (cssFiles.length === 0) {
          console.log("[concat-styles] No CSS files found in", inputDir);
          return;
        }

        // Concatenate all CSS files with section headers
        const sections = cssFiles.map((file) => {
          const content = fs.readFileSync(path.join(inputDir, file), "utf-8");
          return `/* ============================================================\n   ${file}\n   ============================================================ */\n\n${content}`;
        });

        const combined = sections.join("\n\n");
        fs.writeFileSync(outputFile, combined, "utf-8");
        console.log(`[concat-styles] Wrote ${outputFile} (${cssFiles.length} files, ${combined.length} bytes)`);
      });
    },
  };
}

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtinModules,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: prod ? "main.js" : `${PLUGIN_DEV_DIR}/main.js`,
  plugins: [
    concatStylesPlugin({
      inputDir: "src/styles",
      outputFile: "styles.css",
    }),
  ],
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
