name: Release Obsidian plugin

on:
  push:
    # Triggers the workflow when a tag is pushed (e.g. `1.0.0` or `v1.0.0`)
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24"

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Lint (Plugin & packages)
        run: npm run lint

      - name: Test MCP
        run: npm test --workspace=packages/mcp

      - name: Build plugin
        run: npm run build

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            main.js
            manifest.json
            styles.css
